/* MAKE SENSE — local-first, build-free browser game. All questions are in data/. */
(() => {
  'use strict';
  const GENRES = ['A','B','C','D'];
  const ACTORS = {
    A:{name:'ロジカ',role:'出題者 A',headline:'最初の一戦。',line:'さあ、どれにする？',sub:'勝てば次の出題者へ',icon:'⌕'},
    B:{name:'コレクタ',role:'出題者 B',headline:'次の一戦。',line:'さあ、勝負しよう。',sub:'勝てば次の出題者へ',icon:'✳'},
    C:{name:'モジカ',role:'出題者 C',headline:'続いての一戦。',line:'どれがいいと思う？',sub:'勝てば次の出題者へ',icon:'⌗'},
    D:{name:'ノイズ',role:'出題者 D',headline:'四人目の一戦。',line:'思い切って選んで。',sub:'勝てば4人突破',icon:'✧'}
  };
  const KANA_ROWS = [
    ['あ','い','う','え','お'],['か','き','く','け','こ'],['さ','し','す','せ','そ'],
    ['た','ち','つ','て','と'],['な','に','ぬ','ね','の'],['は','ひ','ふ','へ','ほ'],
    ['ま','み','む','め','も'],['や',null,'ゆ',null,'よ'],['ら','り','る','れ','ろ'],
    ['わ',null,null,null,'を'],['ん',null,null,null,null]
  ];
  const KANA = new Map();
  KANA_ROWS.forEach((row,r)=>row.forEach((v,c)=>{if(v) KANA.set(v,{x:r+1,y:c+1});}));
  const BLOCKED = new Set(['うんこ','うんち']);
  const BOSS_WORDS = new Set(['あんこ','あんよ','ほあん']);
  const STORAGE_KEY='makesense-save-v2';
  const BOSS_DURATION_MS=60000;
  const LOG_CLOCK_RATE=0.2;
  const $=s=>document.querySelector(s);
  const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const cleanWord = w => typeof w==='string' && Array.from(w).length===3 && !BLOCKED.has(w) && [...w].every(ch=>KANA.has(ch));
  // Doubled area, so the comparison is entirely integer-based.
  function area2(word){
    if(!cleanWord(word)) return null;
    const [a,b,c]=[...word].map(k=>KANA.get(k));
    return Math.abs((b.x-a.x)*(c.y-a.y)-(c.x-a.x)*(b.y-a.y));
  }
  const shuffle = values => {const copy=[...values];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]];}return copy;};
  const random = list => list[Math.floor(Math.random()*list.length)];
  const hash = s => [...s].reduce((a,c)=>(Math.imul(a,33)+c.charCodeAt(0))>>>0,5381);
  const byHash = (word,list)=>[...list].sort((a,b)=>hash(word+'|'+a.word)-hash(word+'|'+b.word));
  const groupPairs = w => new Set([w.slice(0,2),w.slice(-2)]);
  const compiled=[], categoryWords=new Map(), dictionary=new Set();
  const invalidQuestions=[];
  let storageOK=true;
  let extraAccepted=0, autogenerated=0;

  function normalizeQuestion(raw,source='curated'){
    if(!raw || !GENRES.includes(raw.genre)) return {error:'genre'};
    const words={enemy:raw.enemy,WIN:raw.win,DRAW:raw.draw,LOSE:raw.lose};
    if(Object.values(words).some(w=>!cleanWord(w)))return {error:'invalid word'};
    if(new Set(Object.values(words)).size!==4)return {error:'duplicate word'};
    const e=area2(raw.enemy),w=area2(raw.win),d=area2(raw.draw),l=area2(raw.lose);
    if(e===0||e===null||w<=e||d!==e||l>=e||w===40||d===40||l===40)return {error:'WIN/DRAW/LOSE or spoiler'};
    const q={id:String(raw.id||`AUTO-${hash(JSON.stringify(words))}`),genre:raw.genre,enemy:raw.enemy,
      win:raw.win,draw:raw.draw,lose:raw.lose,family:raw.family||'',note:raw.note||'',status:raw.status||'',source};
    return {question:q};
  }
  function register(raw,source){
    const r=normalizeQuestion(raw,source);
    if(r.error){invalidQuestions.push({id:raw?.id||'?',reason:r.error});return false;}
    if(compiled.some(q=>q.id===r.question.id || [q.genre,q.enemy,q.win,q.draw,q.lose].join('|')===[r.question.genre,r.question.enemy,r.question.win,r.question.draw,r.question.lose].join('|')))return false;
    compiled.push(r.question);
    [r.question.enemy,r.question.win,r.question.draw,r.question.lose].forEach(w=>dictionary.add(w));
    return true;
  }
  const addCategory=(word,category)=>{
    if(!cleanWord(word)||!category)return;
    if(!categoryWords.has(category))categoryWords.set(category,new Set());
    categoryWords.get(category).add(word);
  };
  function makeGenerated(genre,word,group,tag){
    const allowed=[...new Set(group)].filter(w=>cleanWord(w)&&area2(w)<40);
    // Include the newly added word as enemy when possible; otherwise as an option.
    const enemies=[word,...byHash(word,allowed.filter(w=>w!==word))].filter(w=>area2(w)>0&&area2(w)<40);
    for(const enemy of enemies){
      const others=byHash(word+enemy,allowed.filter(w=>w!==enemy));
      const upper=others.filter(w=>area2(w)>area2(enemy)),equal=others.filter(w=>area2(w)===area2(enemy)),lower=others.filter(w=>area2(w)<area2(enemy));
      if(!upper.length||!equal.length||!lower.length)continue;
      let win=random(upper),draw=random(equal),lose=random(lower);
      if(enemy!==word){
        if(upper.includes(word))win=word;
        else if(equal.includes(word))draw=word;
        else if(lower.includes(word))lose=word;
        else continue;
      }
      const q={id:`AUTO-${genre}-${hash(word+'|'+tag+'|'+enemy).toString(36)}`,genre,enemy,win,draw,lose,
        family:tag,note:'単語データから自動生成',status:'自動生成'};
      if(register(q,'auto')){autogenerated++;return true;}
    }
    return false;
  }
  const DRAFT_KEY='makesense-admin-draft-v1';
  function adminOverrides(){
    let payload=window.MS_ADMIN_DATA||{};
    try{
      const draft=JSON.parse(localStorage.getItem(DRAFT_KEY)||'null');
      if(draft&&Array.isArray(draft.questions)&&Array.isArray(draft.words)&&Array.isArray(draft.disabledIds))payload=draft;
    }catch(err){}
    return {questions:Array.isArray(payload.questions)?payload.questions:[],
      words:Array.isArray(payload.words)?payload.words:[],
      disabledIds:new Set(Array.isArray(payload.disabledIds)?payload.disabledIds:[])};
  }
  function loadBank(){
    const admin=adminOverrides();
    const originals=new Map((window.MS_QUESTIONS||[]).map(q=>[q.id,q]));
    for(const q of admin.questions)if(q&&q.id)originals.set(q.id,q);
    for(const q of originals.values()){
      if(admin.disabledIds.has(q.id))continue;
      if(q.status==='不採用')continue;
      register(q,'curated');
      if(q.genre==='B') [q.enemy,q.win,q.draw,q.lose].forEach(w=>addCategory(w,q.family));
    }
    for(const word of (window.MS_BASE_WORDS||[]))if(cleanWord(word))dictionary.add(word);
    BOSS_WORDS.forEach(w=>dictionary.add(w));dictionary.add('いろん');
    const extras=[...(window.MS_EXTRA_WORDS||[]),...admin.words];
    const fresh=[];
    for(const item of extras){
      const word=typeof item==='string'?item:item?.word;
      if(!cleanWord(word))continue;
      dictionary.add(word);fresh.push({word,tags:Array.isArray(item.tags)?item.tags:[]});extraAccepted++;
      for(const tag of (Array.isArray(item.tags)?item.tags:[]))addCategory(word,tag);
    }
    const all=[...dictionary].filter(w=>area2(w)<40);
    for(const {word,tags} of fresh){
      for(const tag of tags){
        const group=categoryWords.has(tag)?[...categoryWords.get(tag)]:[];
        makeGenerated('B',word,group,tag);
      }
      for(const pair of groupPairs(word)){
        const group=all.filter(w=>groupPairs(w).has(pair));
        makeGenerated('C',word,group,pair);
      }
      makeGenerated('D',word,all,'自由追加');
    }
  }
  loadBank();
  const genrePools = Object.fromEntries(GENRES.map(g=>[g,compiled.filter(q=>q.genre===g)]));
  function initial(){return {v:2,phase:'intro',round:1,stage:0,total:0,wins:0,draws:0,losses:0,
    used:{A:[],B:[],C:[],D:[]},recycles:{A:0,B:0,C:0,D:0},currentId:null,bossInput:'',pending:null,history:[],cleared:false,
    bossRemainingMs:null,bossClockAt:null,bossClockRate:0,hintMode:false,hintOffered:false};}
  function loadSave(){
    try{
      const data=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');
      if(data&&data.v===2&&GENRES.every(g=>Array.isArray(data.used?.[g]))&&Array.isArray(data.history)&&data.round>=1&&data.stage>=0&&data.stage<=4)return {...initial(),...data};
    }catch(err){storageOK=false;}
    return initial();
  }
  let state=loadSave();
  // Saves created before the timed-boss update retain their progress and get a fresh clock.
  if(state.stage>=4&&state.bossRemainingMs===null&&(state.phase==='boss'||(state.phase==='bossResult'&&state.pending?.outcome==='DRAW'))){
    state.bossRemainingMs=BOSS_DURATION_MS;state.bossClockAt=Date.now();state.bossClockRate=state.phase==='boss'?1:0;
  }
  const hintAvailable=()=>state.history.filter(r=>r.genre==='BOSS'&&r.outcome==='LOSE').length>=4;
  const scoreText=w=>{const value=area2(w);return value===null?'':` <span class="word-score">(${value/2})</span>`;};
  const shownWord=w=>esc(w)+(state.hintMode?scoreText(w):'');
  const clockActive=()=>state.stage>=4&&!state.cleared&&state.bossRemainingMs!==null&&(state.phase==='boss'||(state.phase==='bossResult'&&state.pending?.outcome==='DRAW'));
  const clockText=()=>{const sec=Math.max(0,state.bossRemainingMs||0)/1000;const min=Math.floor(sec/60);return `${String(min).padStart(2,'0')}:${(sec-min*60).toFixed(1).padStart(4,'0')}`;};
  function settleClock(now=Date.now()){
    if(state.bossRemainingMs===null||state.bossClockAt===null)return;
    const elapsed=Math.max(0,now-state.bossClockAt);
    if(state.bossClockRate>0)state.bossRemainingMs=Math.max(0,state.bossRemainingMs-elapsed*state.bossClockRate);
    state.bossClockAt=now;
  }
  function setClockRate(rate){
    settleClock();state.bossClockRate=rate;state.bossClockAt=Date.now();save();
    if(state.bossRemainingMs!==null&&state.bossRemainingMs<=0)timeOutBoss();
    updateClockDisplay();
  }
  function beginBossClock(){
    if(state.bossRemainingMs===null)state.bossRemainingMs=BOSS_DURATION_MS;
    setClockRate(1);
  }
  function updateClockDisplay(){
    for(const el of document.querySelectorAll('[data-clock]')){
      el.textContent=clockText();el.classList.toggle('clock--urgent',state.bossRemainingMs!==null&&state.bossRemainingMs<=10000);
    }
  }
  let lastClockSave=0;
  function clockTick(){
    if(state.bossRemainingMs===null||state.bossClockRate===0)return;
    settleClock();updateClockDisplay();
    if(state.bossRemainingMs<=0){timeOutBoss();return;}
    if(Date.now()-lastClockSave>1000){lastClockSave=Date.now();save();}
  }
  function timeOutBoss(){
    if(!clockActive()||state.phase==='clear')return;
    state.bossRemainingMs=0;state.bossClockRate=0;state.bossClockAt=Date.now();
    record('いろん','時間切れ','LOSE','BOSS','FINAL-TIMEOUT');
    state.phase='bossResult';
    const modal=$('#log-dialog');if(modal?.open)modal.close();
    save();render();
  }
  // A saved boss clock is settled before the view is restored. A reloaded dialog is closed.
  if(state.bossRemainingMs!==null){
    settleClock();
    state.bossClockRate=state.phase==='boss'?1:0;
    state.bossClockAt=Date.now();
    if((state.phase==='boss'||(state.phase==='bossResult'&&state.pending?.outcome==='DRAW'))&&state.bossRemainingMs<=0)timeOutBoss();
    else save();
  }
  function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state));storageOK=true;}catch(err){storageOK=false;}}
  function toast(message){const el=$('#toast');if(!el)return;el.textContent=message;el.classList.add('toast--show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('toast--show'),3300);}
  function chooseQuestion(genre,previous){
    let pool=genrePools[genre];
    if(!pool||!pool.length)return null;
    let available=pool.filter(q=>!state.used[genre].includes(q.id));
    if(!available.length){state.used[genre]=[];state.recycles[genre]=(state.recycles[genre]||0)+1;available=pool.filter(q=>q.id!==previous);if(!available.length)available=pool;}
    const curated=available.filter(q=>q.source==='curated');
    // Authored puzzles appear more frequently; newly added words still participate.
    const selection=curated.length&&Math.random()<0.7?curated:available;
    const q=random(selection);
    state.used[genre].push(q.id);state.currentId=q.id;save();return q;
  }
  function currentQuestion(){
    if(state.stage>=4)return null;
    const found=compiled.find(q=>q.id===state.currentId && q.genre===GENRES[state.stage]);
    return found||chooseQuestion(GENRES[state.stage]);
  }
  function record(enemy,chosen,outcome,genre,id){
    state.total++; if(outcome==='WIN')state.wins++;else if(outcome==='DRAW')state.draws++;else state.losses++;
    state.history.push({n:state.total,round:state.round,genre,enemy,chosen,outcome,id,at:new Date().toISOString()});
    state.pending={enemy,chosen,outcome,genre,id};
    save();
  }
  const labelFor = outcome => ({WIN:'WIN',DRAW:'DRAW',LOSE:'LOSE'}[outcome]);
  const heroAvatar = genre => `<div class="avatar avatar--${genre.toLowerCase()}" aria-hidden="true"><span class="avatar__halo"></span><span class="avatar__body"></span><span class="avatar__head"><i class="avatar__eye avatar__eye--l"></i><i class="avatar__eye avatar__eye--r"></i><i class="avatar__smile"></i></span><span class="avatar__sigil">${ACTORS[genre].icon}</span></div>`;
  const word = w => [...w].map(ch=>`<span>${esc(ch)}</span>`).join('');
  const stageTrack = () => `<div class="stage-track" aria-label="4人の対戦進行状況">${GENRES.map((g,i)=>`<div class="stage-step ${i<state.stage?'stage-step--done':i===state.stage?'stage-step--current':''} ${i>state.stage?'stage-step--upcoming':''}"><span class="stage-step__number">${i<state.stage?'✓':g}</span><span class="stage-step__name">${ACTORS[g].name}</span></div>`).join('')}</div>`;
  const tally = () => `<div class="status-figures"><span>${state.round}<small>周目</small></span><i></i><span>${state.total}<small>戦</small></span></div>`;
  function introView(){
    return `<section class="intro">
      <div class="intro__eyebrow"><span class="pulse-dot"></span> THREE WORDS × FOUR CHALLENGERS</div>
      <h1 class="intro__title">MAKE<br><em>SENSE<span>.</span></em></h1>
      <p class="intro__japanese">メイクセンス</p>
      <p class="intro__lead">選ぶのは、<br class="mobile-only">たった三文字。</p>
      <p class="intro__copy">3文字の言葉で、4人の出題者に挑戦。<br>それぞれに勝って、先へ進もう。</p>
      <div class="intro__actions"><button class="button button--primary button--large" data-action="start">${state.total||state.currentId?'続きから始める':'ゲームを始める'}<span aria-hidden="true">↗</span></button><button class="button button--subtle" data-action="rules">遊び方を見る</button></div>
      <div class="intro__hint">${storageOK?'進行状況は、このブラウザに自動保存されます。':'保存機能が利用できません。ブラウザの設定をご確認ください。'}</div>
      <div class="intro__cast-title"><span>THE FOUR CHALLENGERS</span><span>4人の出題者</span></div>
      <div class="cast-grid">${GENRES.map(g=>`<article class="cast-card cast-card--${g.toLowerCase()}">${heroAvatar(g)}<div class="cast-card__code">GENRE ${g}</div><h3>${ACTORS[g].name}</h3></article>`).join('')}</div>
      <p class="intro__bottom">三択にはWIN・DRAW・LOSEが、それぞれひとつ。</p>
    </section>`;
  }
  function battleView(){
    const g=GENRES[state.stage]; const actor=ACTORS[g];const q=currentQuestion();
    if(!q)return `<section class="empty-state"><h1>${g}の問題がありません</h1><p>data/questions.js に、このジャンルの問題を追加してください。</p><button class="button button--primary" data-action="home">トップへ戻る</button></section>`;
    const selections=state.displayOrder && state.displayOrderId===q.id ? state.displayOrder : shuffle(['win','draw','lose']);
    state.displayOrder=selections;state.displayOrderId=q.id;save();
    return `<section class="game-view game-view--${g.toLowerCase()}">
      <div class="game-topline"><div class="breadcrumb">ROUND ${String(state.round).padStart(2,'0')} <span>/</span> ${state.stage+1} OF 4</div>${tally()}</div>
      ${stageTrack()}
      <div class="battle-grid">
        <div class="enemy-panel"><div class="enemy-panel__mark">CHALLENGER <b>${g}</b></div>${heroAvatar(g)}<p class="enemy-panel__role">${actor.role}</p><h1>${actor.name}</h1><p class="enemy-panel__line">「${actor.line}」</p></div>
        <div class="challenge-panel"><div class="challenge-panel__top"><span class="micro-label">YOUR CHALLENGE</span><span class="challenge-panel__seq">QUESTION <span class="challenge-panel__dot">•</span> ${esc(q.id)}</span></div>
          <p class="challenge-panel__prompt">この言葉に<span>勝てる</span>のは？</p>
          <div class="enemy-word" aria-label="相手の言葉：${esc(q.enemy)}">${word(q.enemy)}${state.hintMode?scoreText(q.enemy):''}</div>
          <div class="choice-list">${selections.map((k,i)=>`<button class="choice" data-action="answer" data-choice="${k}" aria-label="選択肢${i+1}、${esc(q[k])}"><span class="choice__index">0${i+1}</span><span class="choice__word">${esc(q[k])}</span><span class="choice__arrow" aria-hidden="true">↗</span></button>`).join('')}</div>
          <p class="challenge-panel__foot">WIN・DRAW・LOSE はそれぞれひとつ。<br>選んだ言葉と結果は、対戦ログに残ります。</p>
        </div>
      </div>
    </section>`;
  }
  function outcomeView(isBoss){
    const r=state.pending;
    if(!r)return introView();
    const win=r.outcome==='WIN',draw=r.outcome==='DRAW';
    const heading=win?(isBoss?'異論を覆した。':'見事、一本。'):draw?'引き分け。':isBoss?'異論は覆せなかった。':'今回は、相手の勝ち。';
    const description=isBoss?(win?'あなたの言葉が、最後の異論を上回った。':draw?'同じ強さ。残り時間を引き継いで再挑戦できる。':r.chosen==='時間切れ'?'制限時間が終了。記録を残して1人目から再挑戦しよう。':'これまでの記録は残ったまま。4人に再び挑もう。'):(win?'次の出題者へ進もう。':'勝利数はそのまま。新しい問題でもう一戦。');
    const button=isBoss?(win?'結果を見る':draw?'再開':'リスタート'):win?'次へ':'もう一戦';
    return `<section class="outcome-view outcome-view--${r.outcome.toLowerCase()}">
      <div class="outcome-view__top">${isBoss?'FINAL BATTLE':`GENRE ${r.genre}`} / BATTLE ${String(state.total).padStart(2,'0')}</div>
      <div class="outcome-view__seal">${r.outcome==='WIN'?'✦':r.outcome==='DRAW'?'＝':'×'}</div>
      <div class="outcome-view__status">${r.outcome}</div><h1>${heading}</h1><p class="outcome-view__desc">${description}</p>
      <div class="outcome-compare"><div><small>相手の言葉</small><strong>${shownWord(r.enemy)}</strong></div><span class="outcome-compare__versus">VS</span><div><small>あなたの言葉</small><strong>${shownWord(r.chosen)}</strong></div></div>${isBoss?`<div class="boss-clock boss-clock--result"><small>残り時間</small><strong data-clock>${clockText()}</strong></div>`:''}
      <div class="outcome-view__actions"><button class="button button--primary button--large" data-action="continue">${button}<span aria-hidden="true">↗</span></button><button class="button button--subtle" data-action="log">ログを確認</button></div>
      <p class="outcome-view__foot">${tally()}</p>
    </section>`;
  }
  const kanaTable = () => `<div class="kana-board" role="group" aria-label="五十音表。右上が『あ』です"><div class="kana-grid">${[0,1,2,3,4].map(v=>[...KANA_ROWS].reverse().map(row=>row[v]).map(k=>k?`<button type="button" class="kana-button" data-action="kana" data-kana="${k}" aria-label="${k}" ${state.bossInput.length>=3?'disabled':''}>${k}</button>`:`<span class="kana-blank" aria-hidden="true"></span>`).join('')).join('')}</div></div>`;
  function bossView(){
    return `<section class="boss-view"><div class="boss-view__mark"><span>FINAL CHALLENGER</span><span>${tally()}</span></div>
      <div class="boss-view__orb"><span>異</span><span>論</span></div>${state.hintMode?`<div class="boss-scoreline">いろん${scoreText('いろん')}</div>`:''}
      <div class="boss-view__center"><span class="micro-label">FINAL BATTLE</span><h1>異論を、覆せ。</h1><p>五十音表から言葉を選び、<br>「異論」に勝てる一般的な三文字の単語を作れ。</p>
        <div class="boss-clock" aria-live="off"><small>残り時間</small><strong data-clock>${clockText()}</strong></div>
        <div class="boss-word-label">YOUR WORD</div><div class="boss-slots">${[0,1,2].map(i=>`<div class="boss-slot ${state.bossInput[i]?'boss-slot--filled':''}">${esc(state.bossInput[i]||'・')}</div>`).join('')}</div>
        <div class="boss-controls"><button type="button" class="button button--subtle button--small" data-action="erase" ${!state.bossInput?'disabled':''}>⌫ ひと文字戻す</button><button type="button" class="button button--subtle button--small" data-action="clear" ${!state.bossInput?'disabled':''}>すべて消す</button></div>
        ${kanaTable()}
        <button type="button" class="button button--primary button--large boss-submit" data-action="submit-boss" ${state.bossInput.length!==3?'disabled':''}>この言葉で挑戦する <span aria-hidden="true">↗</span></button>
        <p class="boss-view__hint">※答えは一般的な三文字の単語です。対戦ログを見返すこともできます。</p>
      </div></section>`;
  }
  function clearView(){
    return `<section class="clear-view"><div class="clear-view__top">CONGRATULATIONS</div><div class="clear-view__spark">✳</div><div class="clear-view__overline">MAKE SENSE</div><h1>異論を、<br>覆しました。</h1><p class="clear-view__sub">あなたの答えが、最後の一言になった。</p>
      <div class="clear-view__metrics"><div><strong>${state.round}<small>周目</small></strong><span>CLEAR ROUND</span></div><div><strong>${state.total}<small>戦</small></strong><span>TOTAL BATTLES</span></div></div>
      <div class="clear-view__stats"><span>WIN ${state.wins}</span><span>DRAW ${state.draws}</span><span>LOSE ${state.losses}</span></div>
      <div class="clear-view__actions"><button class="button button--primary button--large" data-action="share">Xでクリアをシェア <span aria-hidden="true">↗</span></button><button class="button button--subtle" data-action="copy-share">投稿文をコピー</button><button class="button button--subtle" data-action="log">対戦ログを見る</button></div>
      <div class="clear-view__spoiler">SNS投稿には、最後の正解ワードを含めません。</div>
      <button class="clear-view__retry" data-action="reset">最初からプレイする ↺</button></section>`;
  }
  function hintChoiceView(){
    return `<section class="hint-view"><div class="hint-view__eyebrow">NEW OPTION UNLOCKED</div>
      <div class="hint-view__icon">✳</div><h1>ヒントモード解放</h1>
      <p>ここからは、相手のお題と対戦ログに言葉の数値を表示できます。<br>選択肢の数値と計算方法は表示されません。</p>
      <div class="hint-view__actions"><button class="button button--primary button--large" data-action="hint-choose" data-enabled="yes">ヒントを使う</button>
      <button class="button button--subtle" data-action="hint-choose" data-enabled="no">使わずに挑む</button></div>
      <p class="hint-view__note">後から画面上部で切り替えられます。</p></section>`;
  }
  function render(){
    const el=$('#app');
    el.innerHTML=state.phase==='intro'?introView():state.phase==='battle'?battleView():state.phase==='result'?outcomeView(false):state.phase==='boss'?bossView():state.phase==='bossResult'?outcomeView(true):state.phase==='clear'?clearView():state.phase==='hintChoice'?hintChoiceView():introView();
    $('#log-count').textContent=state.history.length;
    const hintControl=$('#hint-toggle');
    if(hintControl){hintControl.hidden=!hintAvailable();hintControl.textContent=state.hintMode?'ヒント ON':'ヒント OFF';hintControl.setAttribute('aria-pressed',String(state.hintMode));}
    updateClockDisplay();
    document.body.dataset.phase=state.phase;
    window.scrollTo({top:0,behavior:'instant'});
  }
  function answer(key){
    if(state.phase!=='battle')return;
    const q=currentQuestion(); if(!q||!['win','draw','lose'].includes(key))return;
    const result={win:'WIN',draw:'DRAW',lose:'LOSE'}[key];
    record(q.enemy,q[key],result,q.genre,q.id);state.phase='result';save();render();
  }
  function submitBoss(){
    if(state.phase!=='boss'||state.bossInput.length!==3)return;
    settleClock();if(state.bossRemainingMs<=0){timeOutBoss();return;}
    const chosen=state.bossInput;
    if(!dictionary.has(chosen)){toast('登録されていない言葉です。一般的な三文字の単語を入力してください。');return;}
    const score=area2(chosen);const boss=area2('いろん');
    if(score===null){toast('五十音表から三文字を選んでください。');return;}
    const outcome=score>boss?'WIN':score===boss?'DRAW':'LOSE';
    // All registered, ordinary three-kana words that exceed the boss score can clear.
    // The canonical answers are あんこ / あんよ / ほあん; additional valid answers are allowed.
    record('いろん',chosen,outcome,'BOSS','FINAL');state.phase='bossResult';state.bossClockRate=0;save();render();
  }
  function proceed(){
    if(!state.pending)return;
    const outcome=state.pending.outcome;const boss=state.phase==='bossResult';
    if(boss){
      if(outcome==='WIN'){state.phase='clear';state.cleared=true;}
      else if(outcome==='DRAW'){state.bossInput='';state.phase='boss';state.pending=null;beginBossClock();render();return;}
      else {state.round++;state.stage=0;state.currentId=null;state.displayOrderId=null;state.bossInput='';state.bossRemainingMs=null;state.bossClockAt=null;state.bossClockRate=0;state.phase=hintAvailable()&&!state.hintOffered?'hintChoice':'battle';if(state.phase==='hintChoice')state.hintOffered=true;}
    }else if(outcome==='WIN'){
      state.stage++;
      state.currentId=null;state.displayOrderId=null;
      state.phase=state.stage>=4?'boss':'battle';if(state.phase==='boss'){state.bossRemainingMs=null;beginBossClock();}
    }else{
      const genre=GENRES[state.stage];const previous=state.currentId;state.currentId=null;state.displayOrderId=null;
      chooseQuestion(genre,previous);state.phase='battle';
    }
    state.pending=null;save();render();
  }
  function openModal(id){
    const modal=$(id);if(!modal||typeof modal.showModal!=='function'||modal.open)return;
    if(id==='#log-dialog'&&clockActive()&&(state.phase==='boss'||state.phase==='bossResult'))setClockRate(LOG_CLOCK_RATE);
    if(state.phase==='bossResult'&&state.pending?.id==='FINAL-TIMEOUT')return;
    modal.showModal();updateClockDisplay();
  }
  function logClosed(){
    if(clockActive()&&(state.phase==='boss'||state.phase==='bossResult'))setClockRate(state.phase==='boss'?1:0);
  }
  function renderLog(filter='ALL'){
    $('#log-timer').innerHTML=clockActive()&&(state.phase==='boss'||state.phase==='bossResult')?`<div class="log-clock"><span>ログ閲覧中 TIME ×0.2</span><strong data-clock>${clockText()}</strong></div>`:'';
    $('#log-summary').innerHTML=`<div><b>${state.total}</b><small>総対戦</small></div><div><b>${state.wins}</b><small>WIN</small></div><div><b>${state.draws}</b><small>DRAW</small></div><div><b>${state.losses}</b><small>LOSE</small></div>`;
    const filters=[['ALL','すべて'],['A','A'],['B','B'],['C','C'],['D','D']];
    if(state.stage>=4||state.history.some(r=>r.genre==='BOSS')||state.cleared)filters.push(['BOSS','異論']);
    $('#log-filters').innerHTML=filters.map(([k,label])=>`<button type="button" data-log-filter="${k}" class="log-filter ${filter===k?'log-filter--active':''}">${label}</button>`).join('');
    const results=state.history.filter(x=>filter==='ALL'||x.genre===filter).slice().reverse();
    $('#log-list').innerHTML=results.length?results.map(r=>`<div class="log-entry"><span class="log-entry__index">#${String(r.n).padStart(3,'0')} <span>／ ${r.round}周目</span></span><span class="log-entry__words">${shownWord(r.enemy)} <i>VS</i> ${shownWord(r.chosen)}</span><span class="log-entry__outcome log-entry__outcome--${r.outcome.toLowerCase()}">${r.outcome}</span><span class="log-entry__genre">${r.genre==='BOSS'?'異論':`GENRE ${r.genre}`}</span></div>`).join(''):`<div class="log-empty">まだ記録はありません。<br>まずは一戦、挑んでみよう。</div>`;
  }
  const shareText = () => `『メイクセンス』を${state.round}周目・${state.total}戦でクリア！\n異論を覆しました。\n#メイク_センス`;
  const liveUrl=()=>/^https?:$/.test(window.location.protocol)&&!['localhost','127.0.0.1'].includes(window.location.hostname)&&!window.location.hostname.endsWith('.test')?window.location.origin+window.location.pathname:'';
  const announcementUrl=()=>{
    let data=window.MS_ADMIN_DATA||{};
    try{
      const local=JSON.parse(localStorage.getItem(DRAFT_KEY)||'null');
      if(local&&Array.isArray(local.questions)&&Array.isArray(local.words)&&Array.isArray(local.disabledIds))data=local;
    }catch(err){}
    const url=String(data.announcementUrl||'').trim();
    return /^https:\/\/(?:www\.)?(?:x\.com|twitter\.com)\/[a-zA-Z0-9_]+\/status\/\d+(?:\/)?(?:\?[^\s#]*)?$/.test(url)?url:'';
  };
  // X usually renders a post URL included in the text as a quote card, but X controls presentation.
  const shareBody=()=>shareText()+(announcementUrl()?'\n'+announcementUrl():liveUrl()?'\n'+liveUrl():'');
  function share(){
    const url=`https://twitter.com/intent/tweet?text=${encodeURIComponent(shareBody())}`;
    const opened=window.open(url,'_blank','noopener,noreferrer');
    if(!opened)window.location.href=url;
  }
  async function copyShare(){
    try{await navigator.clipboard.writeText(shareBody());toast('クリア投稿文をコピーしました。');}
    catch(e){try{const ta=document.createElement('textarea');ta.value=shareBody();document.body.append(ta);ta.select();document.execCommand('copy');ta.remove();toast('クリア投稿文をコピーしました。');}catch(err){toast('コピーできませんでした。');}}
  }
  function reset(){
    if(!confirm('現在の進行状況と対戦ログをすべて削除して、最初から始めますか？'))return;
    state=initial();save();render();toast('新しいゲームを始められます。');
  }
  function goHome(){if(state.phase==='boss'||state.phase==='bossResult'){toast('最終戦の途中はトップに戻れません。');return;}state.phase='intro';save();render();}
  function start(){
    if(state.cleared){state.phase='clear';}
    else if(state.pending){state.phase=state.pending.genre==='BOSS'?'bossResult':'result';}
    else if(state.phase==='hintChoice')return;
    else if(state.stage>=4){state.phase='boss';if(state.bossRemainingMs===null)beginBossClock();else setClockRate(1);}
    else state.phase='battle';
    save();render();
  }
  document.addEventListener('click',e=>{
    const global=e.target.closest('[data-global]');
    if(global){const action=global.dataset.global;
      if(action==='home')goHome();else if(action==='rules'){if(state.phase==='boss'){toast('最終戦の途中はルール画面を開けません。');return;}openModal('#rules-dialog');}
      else if(action==='log'){renderLog();openModal('#log-dialog');}
      else if(action==='hint-toggle'&&hintAvailable()){state.hintMode=!state.hintMode;save();render();if($('#log-dialog').open)renderLog();toast(state.hintMode?'ヒントモード ON':'ヒントモード OFF');}
      else if(action==='reset')reset();return;}
    const filter=e.target.closest('[data-log-filter]');if(filter){renderLog(filter.dataset.logFilter);return;}
    const actionEl=e.target.closest('[data-action]');if(!actionEl)return;
    const action=actionEl.dataset.action;
    if(action==='hint-choose'&&state.phase==='hintChoice'){state.hintMode=actionEl.dataset.enabled==='yes';state.phase='battle';save();render();}
    else if(action==='start')start();else if(action==='rules')openModal('#rules-dialog');else if(action==='log'){renderLog();openModal('#log-dialog');}
    else if(action==='answer')answer(actionEl.dataset.choice);else if(action==='continue')proceed();
    else if(action==='kana'&&state.phase==='boss'&&state.bossInput.length<3){state.bossInput+=actionEl.dataset.kana;save();render();}
    else if(action==='erase'&&state.phase==='boss'){state.bossInput=state.bossInput.slice(0,-1);save();render();}
    else if(action==='clear'&&state.phase==='boss'){state.bossInput='';save();render();}
    else if(action==='submit-boss')submitBoss();else if(action==='share')share();else if(action==='copy-share')copyShare();
    else if(action==='reset')reset();else if(action==='home')goHome();
  });
  document.addEventListener('keydown',e=>{
    if(document.querySelector('dialog[open]'))return;
    if(state.phase==='battle'&&['1','2','3'].includes(e.key)){
      const button=$('.choice-list');const choice=button?.querySelectorAll('[data-choice]')[Number(e.key)-1];if(choice)answer(choice.dataset.choice);
    }
    if(state.phase==='boss'&&e.key==='Backspace'){e.preventDefault();state.bossInput=state.bossInput.slice(0,-1);save();render();}
    if(state.phase==='boss'&&e.key==='Enter'&&state.bossInput.length===3)submitBoss();
  });
  document.querySelectorAll('dialog').forEach(dialog=>dialog.addEventListener('click',e=>{
    if(e.target===dialog)dialog.close();
  }));
  $('#log-dialog').addEventListener('close',logClosed);
  setInterval(clockTick,100);
  // Manual verification is available to developers in the console without showing the answer in the game UI.
  window.MS_DEV={getStats:()=>({curated:compiled.filter(q=>q.source==='curated').length,autogenerated,extraAccepted,pools:Object.fromEntries(GENRES.map(g=>[g,genrePools[g].length])),invalidQuestions}),score:area2};
  render();
})();
